args: ["tunnel", "--no-autoupdate", "--hello-world"]

livenessProbe: []

readinessProbe: []

startupProbe: []

credentials:
  create: true
  secretName: cloudflared-credentials
  key: credentials.json
  value: ""

tunnel_id:
  create: true
  secretName: cloudflared-tunnel
  key: TUNNEL_KEY
  value: ""

config:
  create: true
  name: cloudflared-config
  key: config.yaml
  value: ""
