credentials:
  create: true
  secretName: cloudflared-credentials
  key: credentials.json
  value: |
    {
      "AccountTag": "FakeAccountTag",
      "TunnelSecret": "FakeTunnelSecret",
      "TunnelID": "FakeTunnelId"
    }

tunnel_id:
  create: true
  secretName: cloudflared-tunnel
  key: TUNNEL_KEY
  value: "TEST_TUNNEL_KEY"

config:
  create: true
  name: cloudflared-config
  key: config.yaml
  value: |
    ---
    originRequest:
      originServerName: "fake.dns"
    
    ingress:
      - hostname: "fake.dev"
        service: fake-service.svc.cluster.local
      - service: http_status:404
