---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Lint Chart"

on:
  workflow_call:
    inputs:
      chartsToLint:
        required: false
        type: string
        default: ""

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.3 # renovate: datasource=github-releases depName=helm packageName=helm/helm

      - uses: actions/setup-python@v5.3.0
        with:
          python-version-file: .python-version

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.6.1
        with:
          version: v3.11.0 # renovate: datasource=github-releases depName=chart-testing packageName=helm/chart-testing

      - name: Run lint
        run: ct lint --config .github/ci/ct-lint.yaml --charts "${{ inputs.chartsToLint }}"