{{- if .Values.tunnel_id.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "cloudflared.tunnelIdSecretName" .) .Values.tunnel_id.secretName }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "cloudflared.labels" . | nindent 4 }}
stringData:
  {{ .Values.tunnel_id.key }}: {{ .Values.tunnel_id.value | quote}}
{{- end -}}