{{- if .Values.credentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "cloudflared.credentialsSecretName" .) .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "cloudflared.labels" . | nindent 4 }}
stringData:
  {{ .Values.credentials.key }}: |-
  {{- with .Values.credentials.value }}
  {{- if kindIs "string" . }}
    {{- tpl . $ | nindent 4 }}
  {{- else }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end -}}