{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "cloudflared.fullname" .) .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "cloudflared.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{ toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonLabels }}
    {{ toYaml .Values.global.commonLabels | nindent 4 }}
    {{- end }}
  
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- toYaml .Values.global.commonAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}

spec:
  type: {{ .Values.service.type }}

  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}

  ports:
    {{- with .Values.service.port }}
    - port: {{ . }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}

  selector:
    {{- include "cloudflared.selectorLabels" . | nindent 4 }}

{{- end }}