{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudflared.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "cloudflared.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.labels }}
    {{ toYaml .Values.serviceAccount.labels | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonLabels }}
    {{ toYaml .Values.global.commonLabels | nindent 4 }}
    {{- end }}

  {{- if or .Values.serviceAccount.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- toYaml .Values.global.commonAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}