---
  # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
  name: "Lint and Test Charts"

  on:
    push:
      branches:
        - main
        - 'renovate/**'
    pull_request:

    merge_group:

  concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
    cancel-in-progress: true

  jobs:
    lint-chart:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            fetch-depth: 0

        - name: Install Helm
          uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
          with:
            version: v3.16.3 # renovate: datasource=github-releases depName=helm packageName=helm/helm

        - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
          with:
            python-version-file: .python-version

        - name: Install chart-testing
          uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1
          with:
            version: v3.11.0 # renovate: datasource=github-releases depName=chart-testing packageName=helm/chart-testing

        - name: Run lint
          run: ct lint --config .github/ct.yaml