---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Pull Request: Validate"

on:
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  get-changed-charts:
    uses: ewatkins/helm-charts/.github/workflows/sub-workflows/get-changed-charts.yaml@main

  lint-charts:
    needs: ["get-changed-charts"]
    if: ${{ needs.get-changed-charts.outputs.addedOrModified == 'true' }}
    uses: ewatkins/helm-charts/.github/workflows/sub-workflows/lint.yaml@main
    with:
      chartsToLint: "${{ needs.get-changed-charts.outputs.addedOrModifiedCharts }}"
  
  kubeconform-charts:
    needs: ["get-changed-charts", "lint-charts"]
    if: ${{ needs.get-changed-charts.outputs.addedOrModified == 'true' }}
    uses: ewatkins/helm-charts/.github/workflows/sub-workflows/kubeconform.yaml@main
    with:
      chartsToKubeconform: "${{ needs.get-changed-charts.outputs.addedOrModifiedCharts }}"

  install-chart:
    needs: ["get-changed-charts", "lint-charts", "kubeconform-charts"]
    if: ${{ needs.get-changed-charts.outputs.addedOrModified == 'true' }}
    uses: ewatkins/helm-charts/.github/workflows/sub-workflows/install-chart.yaml@main
    with:
      chartsToInstall: "${{ needs.get-changed-charts.outputs.addedOrModifiedCharts }}"