---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Subflow: Release Charts"

on:
  workflow_call:
    inputs:
      chartsToRelease:
        required: false
        type: string
        default: ""

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.3 # renovate: datasource=github-releases depName=helm packageName=helm/helm

      - name: Build chart dependencies
        run: |
          for dir in charts/*/
          do
              (cd ${dir}; helm dependency build)
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          version: v1.6.1 # renovate: datasource=github-releases depName=helm packageName=helm/chart-releaser-action
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: false  # TODO
          CR_SKIP_EXISTING: true